---
- name: Unpdate Ngnix
  hosts: ngnix
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
  - name: UnInstall wireshark
    apt:
      name: wireshark-qt
      state: absent
      autoremove: yes
      purge: yes
      autoclean: yes
