---
- name: Update ngnix
  hosts: ngnix
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
  - name: update apt repo
    apt:
      update_cache: yes
  
  - name: UnInstall wireshark
    ansible.builtin.apt:
      name: application_name
      state: absent
      update_cache: yes
     