---
- name: Update ngnix
  hosts: ngnix
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
  - name: update apt repo
    apt:
      update_cache: yes
  
  - name: Install wireshark
    apt:
      name: wireshark
      state: absent
     